title: Observability for Dummies
tagline: Unlocking the Secrets of Observability - Simplifying Complexity for Everyone
description: A comprehensive guide for all things Observability
cover: /cover.jpg

categories_path: /categories/
tags_path: /tags/
